apiVersion : apps/v1
kind: Deployment
metadata:
  name: pcarreiraspipelinesjavascriptdocker 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pcarreiraspipelinesjavascriptdocker
  template:
    metadata:
      labels:
        app: pcarreiraspipelinesjavascriptdocker 
    spec:
      containers:
        - name: pcarreiraspipelinesjavascriptdocker 
          image: agoracicdcontainerregistry.azurecr.io/pcarreiraspipelinesjavascriptdocker
          ports:
          - containerPort: 8080
