apiVersion: v1
kind: Service
metadata:
    name: pcarreiraspipelinesjavascriptdocker
spec:
    type: LoadBalancer
    ports:
    - port: 5005 
    selector:
        app: pcarreiraspipelinesjavascriptdocker