apiVersion: v1
kind: Service
metadata:
    name: pcarreirascitesting
    namespace: pcarreiras-debug
spec:
    type: LoadBalancer
    ports:
    - port: 9080 
    selector:
        app: pcarreirascitesting